language: d

sudo: false

d:
  - dmd #-2.070.1
  - dmd-2.069.2
  - dmd-2.068.2
  - dmd-2.067.1
  - dmd-2.065.0
  - dmd-2.066.1
  - gdc-4.8.2
  - gdc-4.9.0
  - ldc-0.14.0
  - ldc-0.15.1
  - ldc-0.16.0
  - ldc
  - ldc-1.0.0-beta2
